# Generated by Django 5.2.12 on 2026-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_type',
            field=models.CharField(choices=[('google', 'Google'), ('email', 'Email')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
