# Generated by Django 5.2.12 on 2026-08-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_is_active_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='visit_proofs/')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('location_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_proofs', to='api.locationlog')),
            ],
        ),
    ]
