# Generated by Django 5.2.12 on 2026-08-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trackingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profiles/'),
        ),
    ]
