# Generated by Django 5.2.12 on 2026-09-02 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employee_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('gps_off', 'GPS Off'), ('gps_on', 'GPS On'), ('internet_off', 'Internet Off'), ('internet_on', 'Internet On')], max_length=30)),
                ('event_time', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_events', to='api.employee')),
            ],
        ),
    ]
